// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/reijo1337/online-library-rsoi2/clients (interfaces: BooksPartInterface)

// Package mock_clients is a generated GoMock package.
package mock_clients

import (
	gomock "github.com/golang/mock/gomock"
	clients "github.com/reijo1337/online-library-rsoi2/clients"
	reflect "reflect"
)

// MockBooksPartInterface is a mock of BooksPartInterface interface
type MockBooksPartInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBooksPartInterfaceMockRecorder
}

// MockBooksPartInterfaceMockRecorder is the mock recorder for MockBooksPartInterface
type MockBooksPartInterfaceMockRecorder struct {
	mock *MockBooksPartInterface
}

// NewMockBooksPartInterface creates a new mock instance
func NewMockBooksPartInterface(ctrl *gomock.Controller) *MockBooksPartInterface {
	mock := &MockBooksPartInterface{ctrl: ctrl}
	mock.recorder = &MockBooksPartInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockBooksPartInterface) EXPECT() *MockBooksPartInterfaceMockRecorder {
	return m.recorder
}

// AddNewBook mocks base method
func (m *MockBooksPartInterface) AddNewBook(arg0 clients.Book) (int32, error) {
	ret := m.ctrl.Call(m, "AddNewBook", arg0)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNewBook indicates an expected call of AddNewBook
func (mr *MockBooksPartInterfaceMockRecorder) AddNewBook(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewBook", reflect.TypeOf((*MockBooksPartInterface)(nil).AddNewBook), arg0)
}

// ChangeBookStatusByID mocks base method
func (m *MockBooksPartInterface) ChangeBookStatusByID(arg0 int32, arg1 bool) error {
	ret := m.ctrl.Call(m, "ChangeBookStatusByID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeBookStatusByID indicates an expected call of ChangeBookStatusByID
func (mr *MockBooksPartInterfaceMockRecorder) ChangeBookStatusByID(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeBookStatusByID", reflect.TypeOf((*MockBooksPartInterface)(nil).ChangeBookStatusByID), arg0, arg1)
}

// GetBookByID mocks base method
func (m *MockBooksPartInterface) GetBookByID(arg0 int32) (*clients.Book, error) {
	ret := m.ctrl.Call(m, "GetBookByID", arg0)
	ret0, _ := ret[0].(*clients.Book)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookByID indicates an expected call of GetBookByID
func (mr *MockBooksPartInterfaceMockRecorder) GetBookByID(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookByID", reflect.TypeOf((*MockBooksPartInterface)(nil).GetBookByID), arg0)
}
