// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Writer struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Writer) Reset()         { *m = Writer{} }
func (m *Writer) String() string { return proto.CompactTextString(m) }
func (*Writer) ProtoMessage()    {}
func (*Writer) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *Writer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Writer.Unmarshal(m, b)
}
func (m *Writer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Writer.Marshal(b, m, deterministic)
}
func (m *Writer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Writer.Merge(m, src)
}
func (m *Writer) XXX_Size() int {
	return xxx_messageInfo_Writer.Size(m)
}
func (m *Writer) XXX_DiscardUnknown() {
	xxx_messageInfo_Writer.DiscardUnknown(m)
}

var xxx_messageInfo_Writer proto.InternalMessageInfo

func (m *Writer) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Writer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Book struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Author               *Writer  `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	Free                 bool     `protobuf:"varint,4,opt,name=Free,proto3" json:"Free,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetAuthor() *Writer {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Book) GetFree() bool {
	if m != nil {
		return m.Free
	}
	return false
}

type NothingBooks struct {
	Dummy                bool     `protobuf:"varint,1,opt,name=dummy,proto3" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NothingBooks) Reset()         { *m = NothingBooks{} }
func (m *NothingBooks) String() string { return proto.CompactTextString(m) }
func (*NothingBooks) ProtoMessage()    {}
func (*NothingBooks) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *NothingBooks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NothingBooks.Unmarshal(m, b)
}
func (m *NothingBooks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NothingBooks.Marshal(b, m, deterministic)
}
func (m *NothingBooks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NothingBooks.Merge(m, src)
}
func (m *NothingBooks) XXX_Size() int {
	return xxx_messageInfo_NothingBooks.Size(m)
}
func (m *NothingBooks) XXX_DiscardUnknown() {
	xxx_messageInfo_NothingBooks.DiscardUnknown(m)
}

var xxx_messageInfo_NothingBooks proto.InternalMessageInfo

func (m *NothingBooks) GetDummy() bool {
	if m != nil {
		return m.Dummy
	}
	return false
}

type WriterBookName struct {
	Writer               string   `protobuf:"bytes,1,opt,name=Writer,proto3" json:"Writer,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WriterBookName) Reset()         { *m = WriterBookName{} }
func (m *WriterBookName) String() string { return proto.CompactTextString(m) }
func (*WriterBookName) ProtoMessage()    {}
func (*WriterBookName) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{3}
}

func (m *WriterBookName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WriterBookName.Unmarshal(m, b)
}
func (m *WriterBookName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WriterBookName.Marshal(b, m, deterministic)
}
func (m *WriterBookName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WriterBookName.Merge(m, src)
}
func (m *WriterBookName) XXX_Size() int {
	return xxx_messageInfo_WriterBookName.Size(m)
}
func (m *WriterBookName) XXX_DiscardUnknown() {
	xxx_messageInfo_WriterBookName.DiscardUnknown(m)
}

var xxx_messageInfo_WriterBookName proto.InternalMessageInfo

func (m *WriterBookName) GetWriter() string {
	if m != nil {
		return m.Writer
	}
	return ""
}

func (m *WriterBookName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type BookInsert struct {
	BookName             string   `protobuf:"bytes,1,opt,name=BookName,proto3" json:"BookName,omitempty"`
	AuthorName           string   `protobuf:"bytes,2,opt,name=AuthorName,proto3" json:"AuthorName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookInsert) Reset()         { *m = BookInsert{} }
func (m *BookInsert) String() string { return proto.CompactTextString(m) }
func (*BookInsert) ProtoMessage()    {}
func (*BookInsert) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{4}
}

func (m *BookInsert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookInsert.Unmarshal(m, b)
}
func (m *BookInsert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookInsert.Marshal(b, m, deterministic)
}
func (m *BookInsert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookInsert.Merge(m, src)
}
func (m *BookInsert) XXX_Size() int {
	return xxx_messageInfo_BookInsert.Size(m)
}
func (m *BookInsert) XXX_DiscardUnknown() {
	xxx_messageInfo_BookInsert.DiscardUnknown(m)
}

var xxx_messageInfo_BookInsert proto.InternalMessageInfo

func (m *BookInsert) GetBookName() string {
	if m != nil {
		return m.BookName
	}
	return ""
}

func (m *BookInsert) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

type SomeID struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SomeID) Reset()         { *m = SomeID{} }
func (m *SomeID) String() string { return proto.CompactTextString(m) }
func (*SomeID) ProtoMessage()    {}
func (*SomeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{5}
}

func (m *SomeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SomeID.Unmarshal(m, b)
}
func (m *SomeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SomeID.Marshal(b, m, deterministic)
}
func (m *SomeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SomeID.Merge(m, src)
}
func (m *SomeID) XXX_Size() int {
	return xxx_messageInfo_SomeID.Size(m)
}
func (m *SomeID) XXX_DiscardUnknown() {
	xxx_messageInfo_SomeID.DiscardUnknown(m)
}

var xxx_messageInfo_SomeID proto.InternalMessageInfo

func (m *SomeID) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type ChangeStatus struct {
	BookID               int32    `protobuf:"varint,1,opt,name=BookID,proto3" json:"BookID,omitempty"`
	NewStatus            bool     `protobuf:"varint,2,opt,name=NewStatus,proto3" json:"NewStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeStatus) Reset()         { *m = ChangeStatus{} }
func (m *ChangeStatus) String() string { return proto.CompactTextString(m) }
func (*ChangeStatus) ProtoMessage()    {}
func (*ChangeStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{6}
}

func (m *ChangeStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeStatus.Unmarshal(m, b)
}
func (m *ChangeStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeStatus.Marshal(b, m, deterministic)
}
func (m *ChangeStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeStatus.Merge(m, src)
}
func (m *ChangeStatus) XXX_Size() int {
	return xxx_messageInfo_ChangeStatus.Size(m)
}
func (m *ChangeStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeStatus proto.InternalMessageInfo

func (m *ChangeStatus) GetBookID() int32 {
	if m != nil {
		return m.BookID
	}
	return 0
}

func (m *ChangeStatus) GetNewStatus() bool {
	if m != nil {
		return m.NewStatus
	}
	return false
}

type AuthRequest struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=AppKey,proto3" json:"AppKey,omitempty"`
	AppSecret            string   `protobuf:"bytes,2,opt,name=AppSecret,proto3" json:"AppSecret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{7}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *AuthRequest) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

type SomeString struct {
	String_              string   `protobuf:"bytes,1,opt,name=String,proto3" json:"String,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SomeString) Reset()         { *m = SomeString{} }
func (m *SomeString) String() string { return proto.CompactTextString(m) }
func (*SomeString) ProtoMessage()    {}
func (*SomeString) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{8}
}

func (m *SomeString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SomeString.Unmarshal(m, b)
}
func (m *SomeString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SomeString.Marshal(b, m, deterministic)
}
func (m *SomeString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SomeString.Merge(m, src)
}
func (m *SomeString) XXX_Size() int {
	return xxx_messageInfo_SomeString.Size(m)
}
func (m *SomeString) XXX_DiscardUnknown() {
	xxx_messageInfo_SomeString.DiscardUnknown(m)
}

var xxx_messageInfo_SomeString proto.InternalMessageInfo

func (m *SomeString) GetString_() string {
	if m != nil {
		return m.String_
	}
	return ""
}

func init() {
	proto.RegisterType((*Writer)(nil), "protocol.Writer")
	proto.RegisterType((*Book)(nil), "protocol.Book")
	proto.RegisterType((*NothingBooks)(nil), "protocol.NothingBooks")
	proto.RegisterType((*WriterBookName)(nil), "protocol.WriterBookName")
	proto.RegisterType((*BookInsert)(nil), "protocol.BookInsert")
	proto.RegisterType((*SomeID)(nil), "protocol.SomeID")
	proto.RegisterType((*ChangeStatus)(nil), "protocol.ChangeStatus")
	proto.RegisterType((*AuthRequest)(nil), "protocol.AuthRequest")
	proto.RegisterType((*SomeString)(nil), "protocol.SomeString")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x95, 0x1c, 0xdb, 0x91, 0x27, 0xc1, 0x94, 0xa9, 0x1b, 0x84, 0x28, 0xc5, 0x2c, 0x39, 0xe8,
	0x50, 0x4c, 0x48, 0x28, 0xb9, 0xf4, 0x22, 0x47, 0x94, 0x88, 0x82, 0x0f, 0xeb, 0x43, 0xcf, 0x6e,
	0xbc, 0xd8, 0xa6, 0x95, 0x56, 0x5d, 0xad, 0x28, 0xfa, 0x3b, 0xfd, 0xa5, 0x65, 0x77, 0xb4, 0x91,
	0x12, 0x27, 0x90, 0xdb, 0xce, 0xe7, 0x9b, 0xf7, 0xde, 0xc2, 0xb4, 0x54, 0x52, 0xcb, 0x07, 0xf9,
	0x7b, 0x61, 0x1f, 0x18, 0xb8, 0x98, 0x7d, 0x86, 0xf1, 0x0f, 0x75, 0xd0, 0x42, 0xe1, 0x14, 0x06,
	0x59, 0x1a, 0xfa, 0x73, 0x3f, 0x1e, 0xf1, 0x41, 0x96, 0x22, 0xc2, 0x70, 0xb5, 0xc9, 0x45, 0x38,
	0x98, 0xfb, 0xf1, 0x84, 0xdb, 0x37, 0xdb, 0xc3, 0x70, 0x29, 0xe5, 0xaf, 0xb7, 0xf4, 0x62, 0x0c,
	0xe3, 0xa4, 0xd6, 0x7b, 0xa9, 0xc2, 0x93, 0xb9, 0x1f, 0x9f, 0x5d, 0xbf, 0x5b, 0x3c, 0x1e, 0x41,
	0x88, 0xbc, 0xad, 0x9b, 0xe9, 0x6f, 0x4a, 0x88, 0x70, 0x38, 0xf7, 0xe3, 0x80, 0xdb, 0x37, 0xbb,
	0x84, 0xf3, 0x95, 0xd4, 0xfb, 0x43, 0xb1, 0x33, 0x80, 0x15, 0xce, 0x60, 0xb4, 0xad, 0xf3, 0xbc,
	0xb1, 0xa0, 0x01, 0xa7, 0x80, 0x7d, 0x85, 0x29, 0xed, 0x32, 0x4d, 0x16, 0xf5, 0xc2, 0xf1, 0xb1,
	0x8d, 0x13, 0xee, 0xd8, 0xbd, 0xc4, 0xe6, 0x1e, 0xc0, 0xcc, 0x65, 0x45, 0x25, 0x94, 0xc6, 0x08,
	0x02, 0xb7, 0xa5, 0x9d, 0x7d, 0x8c, 0xf1, 0x13, 0x00, 0xdd, 0xda, 0xdb, 0xd1, 0xcb, 0xb0, 0x10,
	0xc6, 0x6b, 0x99, 0x8b, 0x2c, 0x7d, 0xae, 0x0c, 0x4b, 0xe1, 0xfc, 0x6e, 0xbf, 0x29, 0x76, 0x62,
	0xad, 0x37, 0xba, 0xae, 0xcc, 0x7d, 0x16, 0xd3, 0xf5, 0xb4, 0x11, 0x7e, 0x84, 0xc9, 0x4a, 0xfc,
	0xa5, 0x26, 0x0b, 0x10, 0xf0, 0x2e, 0xc1, 0xee, 0xe0, 0xcc, 0xa0, 0x71, 0xf1, 0xa7, 0x16, 0x95,
	0x36, 0x4b, 0x92, 0xb2, 0xfc, 0x2e, 0x1a, 0x47, 0x92, 0x22, 0xb3, 0x24, 0x29, 0xcb, 0xb5, 0x78,
	0x50, 0x42, 0xb7, 0x57, 0x76, 0x09, 0x76, 0x09, 0x60, 0x8e, 0x5c, 0x6b, 0x75, 0x28, 0x76, 0x66,
	0x07, 0xbd, 0xdc, 0x0e, 0x8a, 0xae, 0xff, 0x9d, 0xc0, 0x88, 0x24, 0xbf, 0x85, 0x53, 0xa2, 0x58,
	0xe1, 0x45, 0xe7, 0x5d, 0xdf, 0x95, 0xe8, 0xc8, 0x53, 0xe6, 0x5d, 0xf9, 0x98, 0xc0, 0x7b, 0x53,
	0x5e, 0x36, 0x34, 0x9e, 0x14, 0x5b, 0x2b, 0x62, 0xf8, 0xbc, 0xd9, 0xc9, 0x1b, 0x4d, 0xbb, 0x8a,
	0xc9, 0x31, 0x0f, 0x6f, 0xe0, 0x34, 0xd9, 0x6e, 0xed, 0x5f, 0x9b, 0x3d, 0x2d, 0x92, 0x5b, 0x7d,
	0x64, 0x52, 0x9e, 0x79, 0xb8, 0x20, 0x07, 0x97, 0x4d, 0x96, 0xe2, 0x51, 0xfd, 0x05, 0x90, 0x7b,
	0x98, 0x91, 0x37, 0x26, 0x26, 0xa5, 0xed, 0x6c, 0x8f, 0x6d, 0xdf, 0xbb, 0xe8, 0x15, 0x15, 0x98,
	0x87, 0xb7, 0x30, 0x31, 0xbf, 0x96, 0x74, 0x7b, 0x4d, 0xac, 0xa3, 0x03, 0xae, 0x7c, 0xfc, 0x02,
	0x43, 0x23, 0x12, 0x7e, 0xe8, 0x6a, 0x3d, 0xa3, 0xa3, 0xd9, 0x53, 0x16, 0x64, 0x11, 0xf3, 0x7e,
	0x8e, 0x6d, 0xfa, 0xe6, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0xf4, 0x25, 0xf9, 0xd8, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BooksClient is the client API for Books service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BooksClient interface {
	Authors(ctx context.Context, in *NothingBooks, opts ...grpc.CallOption) (Books_AuthorsClient, error)
	BookByAuthorAndName(ctx context.Context, in *WriterBookName, opts ...grpc.CallOption) (*Book, error)
	AddBook(ctx context.Context, in *BookInsert, opts ...grpc.CallOption) (*SomeID, error)
	BookByID(ctx context.Context, in *SomeID, opts ...grpc.CallOption) (*Book, error)
	ChangeBookStatusByID(ctx context.Context, in *ChangeStatus, opts ...grpc.CallOption) (*NothingBooks, error)
	FreeBooks(ctx context.Context, in *NothingBooks, opts ...grpc.CallOption) (Books_FreeBooksClient, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*SomeString, error)
}

type booksClient struct {
	cc *grpc.ClientConn
}

func NewBooksClient(cc *grpc.ClientConn) BooksClient {
	return &booksClient{cc}
}

func (c *booksClient) Authors(ctx context.Context, in *NothingBooks, opts ...grpc.CallOption) (Books_AuthorsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Books_serviceDesc.Streams[0], "/protocol.Books/Authors", opts...)
	if err != nil {
		return nil, err
	}
	x := &booksAuthorsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Books_AuthorsClient interface {
	Recv() (*Writer, error)
	grpc.ClientStream
}

type booksAuthorsClient struct {
	grpc.ClientStream
}

func (x *booksAuthorsClient) Recv() (*Writer, error) {
	m := new(Writer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *booksClient) BookByAuthorAndName(ctx context.Context, in *WriterBookName, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/protocol.Books/BookByAuthorAndName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksClient) AddBook(ctx context.Context, in *BookInsert, opts ...grpc.CallOption) (*SomeID, error) {
	out := new(SomeID)
	err := c.cc.Invoke(ctx, "/protocol.Books/AddBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksClient) BookByID(ctx context.Context, in *SomeID, opts ...grpc.CallOption) (*Book, error) {
	out := new(Book)
	err := c.cc.Invoke(ctx, "/protocol.Books/BookByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksClient) ChangeBookStatusByID(ctx context.Context, in *ChangeStatus, opts ...grpc.CallOption) (*NothingBooks, error) {
	out := new(NothingBooks)
	err := c.cc.Invoke(ctx, "/protocol.Books/ChangeBookStatusByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *booksClient) FreeBooks(ctx context.Context, in *NothingBooks, opts ...grpc.CallOption) (Books_FreeBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Books_serviceDesc.Streams[1], "/protocol.Books/FreeBooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &booksFreeBooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Books_FreeBooksClient interface {
	Recv() (*Book, error)
	grpc.ClientStream
}

type booksFreeBooksClient struct {
	grpc.ClientStream
}

func (x *booksFreeBooksClient) Recv() (*Book, error) {
	m := new(Book)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *booksClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*SomeString, error) {
	out := new(SomeString)
	err := c.cc.Invoke(ctx, "/protocol.Books/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BooksServer is the server API for Books service.
type BooksServer interface {
	Authors(*NothingBooks, Books_AuthorsServer) error
	BookByAuthorAndName(context.Context, *WriterBookName) (*Book, error)
	AddBook(context.Context, *BookInsert) (*SomeID, error)
	BookByID(context.Context, *SomeID) (*Book, error)
	ChangeBookStatusByID(context.Context, *ChangeStatus) (*NothingBooks, error)
	FreeBooks(*NothingBooks, Books_FreeBooksServer) error
	Auth(context.Context, *AuthRequest) (*SomeString, error)
}

func RegisterBooksServer(s *grpc.Server, srv BooksServer) {
	s.RegisterService(&_Books_serviceDesc, srv)
}

func _Books_Authors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NothingBooks)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BooksServer).Authors(m, &booksAuthorsServer{stream})
}

type Books_AuthorsServer interface {
	Send(*Writer) error
	grpc.ServerStream
}

type booksAuthorsServer struct {
	grpc.ServerStream
}

func (x *booksAuthorsServer) Send(m *Writer) error {
	return x.ServerStream.SendMsg(m)
}

func _Books_BookByAuthorAndName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriterBookName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServer).BookByAuthorAndName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Books/BookByAuthorAndName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServer).BookByAuthorAndName(ctx, req.(*WriterBookName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Books_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookInsert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Books/AddBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServer).AddBook(ctx, req.(*BookInsert))
	}
	return interceptor(ctx, in, info, handler)
}

func _Books_BookByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SomeID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServer).BookByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Books/BookByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServer).BookByID(ctx, req.(*SomeID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Books_ChangeBookStatusByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServer).ChangeBookStatusByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Books/ChangeBookStatusByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServer).ChangeBookStatusByID(ctx, req.(*ChangeStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _Books_FreeBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NothingBooks)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BooksServer).FreeBooks(m, &booksFreeBooksServer{stream})
}

type Books_FreeBooksServer interface {
	Send(*Book) error
	grpc.ServerStream
}

type booksFreeBooksServer struct {
	grpc.ServerStream
}

func (x *booksFreeBooksServer) Send(m *Book) error {
	return x.ServerStream.SendMsg(m)
}

func _Books_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BooksServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Books/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BooksServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Books_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Books",
	HandlerType: (*BooksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookByAuthorAndName",
			Handler:    _Books_BookByAuthorAndName_Handler,
		},
		{
			MethodName: "AddBook",
			Handler:    _Books_AddBook_Handler,
		},
		{
			MethodName: "BookByID",
			Handler:    _Books_BookByID_Handler,
		},
		{
			MethodName: "ChangeBookStatusByID",
			Handler:    _Books_ChangeBookStatusByID_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _Books_Auth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Authors",
			Handler:       _Books_Authors_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FreeBooks",
			Handler:       _Books_FreeBooks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocol.proto",
}
